CREATE PROCEDURE CTHOADONNHAPHANG_Ins
	@MAHDNHAPHANG    int = null,
	@MANVL			int = null,
	@SL      		int = null,
	@GIA     		int = null,
	@TONGTIEN 		int = null
AS
	BEGIN TRANSACTION 
	INSERT INTO CTHOADONNHAPHANG(
	[MAHDNHAPHANG],
	[MANVL],
	[SL],
	[GIA],
	[TONGTIEN])
	VALUES
	(@MAHDNHAPHANG,
	@MANVL,
	@SL,
	@GIA,
	@TONGTIEN)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE CTHOADONNHAPHANG_Upd
	@MACTHD			int = null,
	@MAHDNHAPHANG   int = null,
	@MANVL			int = null,
	@SL      		int = null,
	@GIA     		int = null,
	@TONGTIEN 		int = null
AS
	BEGIN TRANSACTION
	UPDATE CTHOADONNHAPHANG SET
	[MAHDNHAPHANG] = @MAHDNHAPHANG,
	[MANVL] = @MANVL,
	[SL] = @SL,
	[GIA] = @GIA,
	[TONGTIEN] = @TONGTIEN
	WHERE [MACTHD] = @MACTHD
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE CTHOADONNHAPHANG_Del
	@MACTHD	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM CTHOADONNHAPHANG 
	WHERE [MACTHD] = @MACTHD
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE CTHOADONNHAPHANG_ByHoaDonNhapHangId
	@MaHDNHAPHANG	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM CTHOADONNHAPHANG 
	WHERE [MAHDNHAPHANG]  = @MaHDNHAPHANG
	COMMIT TRANSACTION

