CREATE PROCEDURE PHIEUYEUCAU_Ins
	@Ngaytao		datetime = null,
	@MaNV			int = null,
	@Status         varchar(1) = null
AS
	BEGIN TRANSACTION 
	INSERT INTO PHIEUYEUCAU(
	[Ngaytao],
	[MaNV],
	[Status])
	VALUES
	(@Ngaytao,
	@MaNV,
	@Status)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUYEUCAU_Upd
	@MaPYC			int = null,
	@Ngaytao		datetime = null,
	@MaNV			int = null,
	@Status         varchar(1) = null
AS
	BEGIN TRANSACTION
	UPDATE PHIEUYEUCAU SET
	[Ngaytao] = @Ngaytao,
	[MaNV] = @MaNV,
	[Status] = @Status
	WHERE [MaPYC] = @MaPYC
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUYEUCAU_Del
	@MaPYC	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM PHIEUYEUCAU 
	WHERE [MaPYC] = @MaPYC
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUYEUCAU_ById
	@MaPYC	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM PHIEUYEUCAU 
	WHERE [MaPYC] = @MaPYC
	COMMIT TRANSACTION


GO
CREATE PROCEDURE PHIEUYEUCAU_Lst1
AS
SELECT * FROM PHIEUYEUCAU 
WHERE [Status] = '1'

GO
CREATE PROCEDURE PHIEUYEUCAU_Lst0
AS
SELECT * FROM PHIEUYEUCAU 
WHERE [Status] = '0'


GO
CREATE PROCEDURE PHIEUYEUCAU_Remove
AS
BEGIN TRANSACTION
	UPDATE PHIEUYEUCAU SET [Status] = '0'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUYEUCAU_Restore
AS
BEGIN TRANSACTION
	UPDATE PHIEUYEUCAU SET [Status] = '1'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0