CREATE PROCEDURE LOAITHUCUONG_Ins
	@TenTU nvarchar(30) = null,
	@Status varchar(1) = null
AS
	BEGIN TRANSACTION 
	INSERT INTO LOAITHUCUONG(
	[TenTU],
	[Status])
	VALUES
	(@TenTU,
	@Status)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE LOAITHUCUONG_Upd
	@MaLoaiTU	int = null,
	@TenTU nvarchar(30) = null,
	@Status varchar(1) = null
AS
	BEGIN TRANSACTION
	UPDATE LOAITHUCUONG SET
	[TenTU] = @TenTU,
	[Status] = @Status
	WHERE [MaLoaiTU] = @MaLoaiTU
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE LOAITHUCUONG_Del
	@MaLoaiTU	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM LOAITHUCUONG 
	WHERE [MaLoaiTU]  = @MaLoaiTU
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE LOAITHUCUONG_ById
	@MaLoaiTU	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM LOAITHUCUONG 
	WHERE [MaLoaiTU]  = @MaLoaiTU
	COMMIT TRANSACTION

GO
CREATE PROCEDURE LOAITHUCUONG_Seach
	@TenTU	nvarchar(30) = null
AS
	BEGIN TRANSACTION
	SELECT * FROM LOAITHUCUONG
	WHERE [TenTU] LIKE '%' + @TenTU + '%' OR  @TenTU IS NULL OR @TenTU= ''
	COMMIT TRANSACTION

GO
CREATE PROCEDURE LOAITHUCUONG_Lst1
AS
SELECT * FROM LOAITHUCUONG 
WHERE [Status] = '1'

GO
CREATE PROCEDURE LOAITHUCUONG_Lst0
AS
SELECT * FROM LOAITHUCUONG 
WHERE [Status] = '0'

GO
CREATE PROCEDURE LOAITHUCUONG_Remove
AS
BEGIN TRANSACTION
	UPDATE LOAITHUCUONG SET [Status] = '0'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE LOAITHUCUONG_Restore
AS
BEGIN TRANSACTION
	UPDATE LOAITHUCUONG SET [Status] = '1'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0