CREATE PROCEDURE PHIEUKIEMKE_Ins
	@CodePKK		varchar(10) = null,
	@Ngaytao		datetime = null,
	@MaNV			int  = null,
	@Status         varchar(1) = null
AS
	BEGIN TRANSACTION 
	INSERT INTO PHIEUKIEMKE(
	[CodePKK],
	[Ngaytao],
	[MaNV],
	[Status])
	VALUES
	(@CodePKK,
	@Ngaytao,
	@MaNV,
	@Status)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUKIEMKE_Upd
	@MaPKK			int = null,
	@CodePKK		varchar(10) = null,
	@Ngaytao		datetime = null,
	@MaNV			int  = null,
	@Status         varchar(1) = null
AS
	BEGIN TRANSACTION
	UPDATE PHIEUKIEMKE SET
	[CodePKK] = @CodePKK,
	[Ngaytao] = @Ngaytao,
	[MaNV] = @MaNV,
	[Status] = @Status
	WHERE [MaPKK] = @MaPKK
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUKIEMKE_Del
	@MaPKK	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM PHIEUKIEMKE 
	WHERE [MaPKK] = @MaPKK
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUKIEMKE_ById
	@MaPKK	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM PHIEUKIEMKE 
	WHERE [MaPKK] = @MaPKK
	COMMIT TRANSACTION

GO
CREATE PROCEDURE PHIEUKIEMKE_Lst1
AS
SELECT * FROM PHIEUKIEMKE 
WHERE [Status] = '1'

GO
CREATE PROCEDURE PHIEUKIEMKE_Lst0
AS
SELECT * FROM PHIEUKIEMKE 
WHERE [Status] = '0'

GO
CREATE PROCEDURE PHIEUKIEMKE_Remove
AS
BEGIN TRANSACTION
	UPDATE PHIEUKIEMKE SET [Status] = '0'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE PHIEUKIEMKE_Restore
AS
BEGIN TRANSACTION
	UPDATE PHIEUKIEMKE SET [Status] = '1'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0