CREATE PROCEDURE HOADONNHAPHANG_Ins
	@CODEHD          varchar(30) = null,
	@TONGTIEN		 int = null,
	@NGAYNHAP        date = null,
	@MANVXACNHAN     int = null,
	@STATUS          varchar(1) = null
AS
	BEGIN TRANSACTION 
	INSERT INTO HOADONNHAPHANG(
	[CODEHD],
	[TONGTIEN],
	[NGAYNHAP],
	[MANVXACNHAN],
	[STATUS])
	VALUES
	(@CODEHD,
	@TONGTIEN,
	@NGAYNHAP,
	@MANVXACNHAN,
	@STATUS)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE HOADONNHAPHANG_Upd
	@MAHDNHAPHANG	 int = null,
	@CODEHD          varchar(30) = null,
	@TONGTIEN		 int = null,
	@NGAYNHAP        date = null,
	@MANVXACNHAN     int = null,
	@STATUS          varchar(1) = null
AS
	BEGIN TRANSACTION
	UPDATE HOADONNHAPHANG SET
	[CODEHD] = @CODEHD,
	[TONGTIEN] = @TONGTIEN,
	[NGAYNHAP] = @NGAYNHAP,
	[MANVXACNHAN] = @MANVXACNHAN,
	[STATUS] = @STATUS
	WHERE [MAHDNHAPHANG] = @MAHDNHAPHANG
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE HOADONNHAPHANG_Del
	@MAHDNHAPHANG	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM HOADONNHAPHANG 
	WHERE [MAHDNHAPHANG]  = @MAHDNHAPHANG
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE HOADONNHAPHANG_ById
	@MAHDNHAPHANG	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM HOADONNHAPHANG 
	WHERE [MAHDNHAPHANG]  = @MAHDNHAPHANG
	COMMIT TRANSACTION

GO
CREATE PROCEDURE HOADONNHAPHANG_Seach
	@CODEHD	nvarchar(30) = null
AS
	BEGIN TRANSACTION
	SELECT * FROM HOADONNHAPHANG
	WHERE [CODEHD] LIKE '%' + @CODEHD + '%' OR  @CODEHD IS NULL OR @CODEHD= ''
	COMMIT TRANSACTION

GO
CREATE PROCEDURE HOADONNHAPHANG_Lst1
AS
SELECT * FROM HOADONNHAPHANG 
WHERE [STATUS] = '1'

GO
CREATE PROCEDURE HOADONNHAPHANG_Lst0
AS
SELECT * FROM HOADONNHAPHANG 
WHERE [STATUS] = '0'


GO
CREATE PROCEDURE HOADONNHAPHANG_Remove
AS
BEGIN TRANSACTION
	UPDATE HOADONNHAPHANG SET [Status] = '0'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE HOADONNHAPHANG_Restore
AS
BEGIN TRANSACTION
	UPDATE HOADONNHAPHANG SET [Status] = '1'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0