CREATE PROCEDURE THUCUONG_Ins
	@TenTU nvarchar(30) = null,
	@MaLoaiTU int = null,
	@Thanhtien	int = null,
	@Status varchar(1) = null
AS
	BEGIN TRANSACTION 
	INSERT INTO THUCUONG(
	[TenTU],
	[MaLoaiTU],
	[Thanhtien],
	[Status])
	VALUES
	(@TenTU,
	@MaLoaiTU,
	@Thanhtien,
	@Status)
	COMMIT TRANSACTION
		SELECT SCOPE_IDENTITY() as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE THUCUONG_Upd
	@MaTU		int = null,
	@TenTU		nvarchar(30) = null,
	@MaLoaiTU	int = null,
	@Thanhtien	int = null,
	@Status		varchar(1) = null
AS
	BEGIN TRANSACTION
	UPDATE THUCUONG SET
	[TenTU] = @TenTU,
	[MaLoaiTU] = @MaLoaiTU,
	[Thanhtien] = @Thanhtien,
	[Status] = @Status
	WHERE [MaTU] = @MaTU
	COMMIT TRANSACTION
		SELECT '1' as Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE THUCUONG_Del
	@MaTU	int = null
AS
	BEGIN TRANSACTION
	DELETE FROM THUCUONG 
	WHERE [MaTU] = @MaTU
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE THUCUONG_ById
	@MaTU	int = null
AS
	BEGIN TRANSACTION
	SELECT * FROM THUCUONG 
	WHERE [MaTU] = @MaTU
	COMMIT TRANSACTION

GO
CREATE PROCEDURE THUCUONG_Seach
	@TenTU	nvarchar(30) = null
AS
	BEGIN TRANSACTION
	SELECT * FROM THUCUONG
	WHERE [TenTU] LIKE '%' + @TenTU + '%' OR  @TenTU IS NULL OR @TenTU= ''
	COMMIT TRANSACTION

GO
CREATE PROCEDURE THUCUONG_Lst1
AS
SELECT * FROM THUCUONG 
WHERE [Status] = '1'

GO
CREATE PROCEDURE THUCUONG_Lst0
AS
SELECT * FROM THUCUONG 
WHERE [Status] = '0'


GO
CREATE PROCEDURE THUCUONG_Remove
AS
BEGIN TRANSACTION
	UPDATE THUCUONG SET [Status] = '0'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0

GO
CREATE PROCEDURE THUCUONG_Restore
AS
BEGIN TRANSACTION
	UPDATE THUCUONG SET [Status] = '1'
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
RETURN 0