GO
CREATE PROCEDURE CTPHIEUYEUCAU_DelByMaPYC
	@MaPYC	varchar(20) = null
AS
	BEGIN TRANSACTION
	DELETE FROM CTPHIEUYEUCAU 
	WHERE [MaPYC] = @MaPYC
	IF @@Error <> 0 GOTO ABORT
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
	ABORT:
		BEGIN
			ROLLBACK TRANSACTION
			SELECT '0' as Result
			RETURN '0'
End
RETURN 0

GO
CREATE PROCEDURE CTPHIEUKIEMKE_DelByMaPKK
	@MaPKK varchar(20) = null
AS
	BEGIN TRANSACTION
	DELETE FROM CTPHIEUKIEMKE
	WHERE [MaPKK] = @MaPKK
	IF @@Error <> 0 GOTO ABORT
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
	ABORT:
		BEGIN
			ROLLBACK TRANSACTION
			SELECT '0' as Result
			RETURN '0'
End
RETURN 0

GO
CREATE PROCEDURE CTHOADONNHAPHANG_DelByMaHDNH
	@MAHDNHAPHANG varchar(20) = null
AS
	BEGIN TRANSACTION
	DELETE FROM CTHOADONNHAPHANG
	WHERE [MAHDNHAPHANG] = @MAHDNHAPHANG
	IF @@Error <> 0 GOTO ABORT
	COMMIT TRANSACTION
		SELECT '1' AS Result
		RETURN '1'
	ABORT:
		BEGIN
			ROLLBACK TRANSACTION
			SELECT '0' as Result
			RETURN '0'
End
RETURN 0
